### ISSUE TITLE
Exception when apply plugin to gradle 5.5

### ISSUE THREAD

**Issue by terribleherbst** [myniva/gradle-s3-build-cache#22]
I try to use the plugin using a gradle project with version 5.5 of the wrapper.

I used to apply the plugin using gradle dsl syntax:
```
plugins {
  id 'java'
  id 'groovy'
  id 'checkstyle'
  id 'jacoco'
  id 'pmd'
   ...
  id "ch.myniva.s3-build-cache" version "0.9.0"
}
```
I did not apply and buildCache configuration.

After applying the plugin I get the following error
```
An exception occurred applying plugin request [id: 'ch.myniva.s3-build-cache', version: '0.9.0']
> Failed to apply plugin [id 'ch.myniva.s3-build-cache']
   > org.gradle.api.internal.project.DefaultProject_Decorated cannot be cast to org.gradle.api.initialization.Settings
```

```
* Exception is:
org.gradle.api.plugins.InvalidPluginException: An exception occurred applying plugin request [id: 'ch.myniva.s3-build-cache', version: '0.9.0']
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.exceptionOccurred(DefaultPluginRequestApplicator.java:247)
```

```
Caused by: java.lang.ClassCastException: org.gradle.api.internal.project.DefaultProject_Decorated cannot be cast to org.gradle.api.initialization.Settings
        at ch.myniva.gradle.caching.s3.AwsS3Plugin.apply(AwsS3Plugin.java:26)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:42)
```

**Comment by trevjonez** [comment]
It looks like you are attempting to apply the plugin to a project but the plugin is implemented over the settings object. (Read: try applying the plugin in your `settings.gradle` file rather than a `build.gradle`)

**Comment by terribleherbst** [comment]
Thanks for your help. Applying the plugin using the settings.gradle works! Great software!
